name: deeplearning
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - absl-py=2.1.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - arrow-cpp=21.0.0
  - async-timeout=5.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0=mkl
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - cuda-cccl=13.0.85
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-runtime=12.4.1
  - cuda-version=13.0
  - datasets=3.3.2
  - dill=0.3.8
  - expat=2.7.3
  - filelock=3.20.0
  - freetype=2.13.3
  - frozenlist=1.8.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - grpcio=1.71.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - khronos-opencl-icd-loader=2024.05.08
  - lcms2=2.16
  - lerc=3.0
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcurl=8.16.0
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.17
  - libffi=3.4.4
  - libgrpc=1.71.0
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown=3.8
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - networkx=3.4.2
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pillow=11.1.0
  - pip=25.3
  - propcache=0.3.1
  - protobuf=5.29.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.51.0
  - sympy=1.14.0
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.15
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - torchaudio==2.5.1
      - torchvision==0.20.1
prefix: ~/envs/deeplearning
